### ISSUE TITLE
Time and date displays

### ISSUE THREAD

**Issue by ChadChapman** [CodeTacoma/TacomaTechAPIFront#9]
Time and date values should be truncated and separated, we don't need to show .0000 of a second @ UTC for Tacoma events.  It's just a bit much.

**Comment by cheneyshreve01** [comment]
Hi @ChadChapman what a cool idea, we definitely need this resource for Tacoma! Would love to help out on this project, is this issue a good place to start?

**Comment by ChadChapman** [comment]
Hi @cheneyshreve , yes that's a great place to start! go for it!

**Comment by GavinThomas1192** [comment]
@cheneyshreve  I didn't see this until now. We should use luxon vs moment, because luxon is the light weight version and I don't see us needing EVERYTHING moment has. You can implement luxon as you suggested pretty much the same as moment, above. Make sure to pull master I've made changes. You would implement the formatting in renderEventTimeDisplay inside components/genericcard.js

**Comment by cheneyshreve01** [comment]
Hi @GavinThomas1192, awesome, thanks!  I didn't know about luxon! I'll pull the changes from master and make the edits recommended above tomorrow morning.

**Comment by GavinThomas1192** [comment]
https://github.com/CodeTacoma/TacomaTechAPIFront/pull/21
Thanks @cheneyshreve for getting this done.
